### ISSUE TITLE
Adding Dependabot

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#326]
I'd like to add [dependabot](https://help.github.com/en/articles/configuring-automated-security-fixes) to our projects.

- [x] miss-islington
- [ ] bedevere
- [ ] the-knights-who-say-ni
- [x] blurb-it
- [x] pythondotorg

Example PR by dependabot: https://github.com/python/miss-islington/pull/232

- [x] Add `dependabot-preview[bot]` to the list of trusted users in our Heroku instance of the-knights-who-say-ni 

Uninstall pyup-io:

- [x] miss-islington
- [ ] bedevere
- [ ] the-knights-who-say-ni
- [x] blurb-it
- [x] pythondotorg

**Comment by brettcannon** [comment]
SGTM

**Comment by webknjaz** [comment]
FTR GitHub has acquired Dependabot and they are integrating things into GitHub itself.

**Comment by Mariatta** [comment]
@encukou I'm having trouble removing pyup.io integration from miss-islington. When I logged in to 
https://pyup.io/account/repos/github/python/miss-islington/, it says that the integration was added by you, so I couldn't remove it.

![Screen Shot 2019-05-27 at 7 25 12 PM](https://user-images.githubusercontent.com/5844587/58446419-8298d200-80b5-11e9-848f-78b76b6cfda2.png)

Can you remove pyup.io integration for python/miss-islington?

Thanks

**Comment by Mariatta** [comment]
Strange, it is the same problem for blurb-it 🤔 

![Screen Shot 2019-05-27 at 7 34 24 PM](https://user-images.githubusercontent.com/5844587/58446698-81b47000-80b6-11e9-9a2c-e4e1e2cde186.png)

**Comment by encukou** [comment]
Hmmm. I don't remember doing that, but here we are :)
I've removed pyup.io integration from `miss-islington` and `blurb-it`.
The integration is also set up for `core-workflow` (added by me), `bedevere` and `the-knights-who-say-ni` (both added by @brettcannon).
Should I remove pyup.io from core-workflow as well?

**Comment by Mariatta** [comment]
Thanks. Hmm technically pyup.io is useless in core-workflow, there is no requirements text or anything like that. Might as well remove it

**Comment by brettcannon** [comment]
If I need to remove anything just let me know.

**Comment by Mariatta** [comment]
> If I need to remove anything just let me know.

I've requested dependabot to be added to bedevere and the-knights-who-say-ni. I don't have the right permission to add it directly.
Once we've added dependabot to those repos, we can remove pyup.io

**Comment by Mariatta** [comment]
Update: I requested automerge feature from dependabot (in closed beta), and it's been enabled for Python org. 🥳

**Comment by brettcannon** [comment]
Yeah, turns out I don't have admin access anymore either.

**Comment by Mariatta** [comment]
@ewdurbin can you look into installing dependabot to bedevere and the-knights-who-say-ni? Thanks.

**Comment by ewdurbin** [comment]
@Mariatta I've reviewed and approved all pending installations for dependably.

**Comment by Mariatta** [comment]
Thanks @ewdurbin. @brettcannon if you can remove pyup from bedevere and the-knights-who-say-ni, then I think this issue can be closed. Thanks.

**Comment by brettcannon** [comment]
@Mariatta I can't as I lack admin access.

@ewdurbin could you remove pyup from https://github.com/python/bedevere and https://github.com/python/the-knights-who-say-ni?

**Comment by ewdurbin** [comment]
Done. All I could find was web hooks configured to notify pyup. Those have been removed.

**Comment by Mariatta** [comment]
Seems like we still don't have dependabot in bedevere and the-knights-who-say-ni 😥
I had to manually merge the PRs from pyup.io.
https://github.com/python/the-knights-who-say-ni/pull/183
https://github.com/python/bedevere/pull/177

**Comment by ewdurbin** [comment]
re Dependabot: I didn't realize we needed to do anything on the Dependabot side, that's been done and initial PRs should be opened soon.

re pyup: It's not clear to me how to further disable it.

**Comment by ewdurbin** [comment]
scratch that, disabled those two repos in pyup.io.

**Comment by Mariatta** [comment]
Thanks! I saw the incoming PRs from dependabot 🚀

**Comment by brettcannon** [comment]
I logged into pyup.io and removed the repos explicitly so that should take care of that. I guess as long as the integrations are removed so they don't have access and we are all good?
